# Generated by Django 5.0 on 2024-03-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestuser',
            name='destination_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='requestuser',
            name='destination_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='requestuser',
            name='origin_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='requestuser',
            name='origin_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
