# Generated by Django 5.0.1 on 2024-01-18 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('otp', models.CharField(max_length=5)),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(2024, 1, 18, 17, 7, 17, 457090, tzinfo=datetime.timezone.utc), editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('city', models.CharField(choices=[('TEHRAN', 'تهران')], max_length=100)),
                ('phone_number', models.BigIntegerField(unique=True)),
                ('user_type', models.CharField(choices=[('RIDER', 'Rider'), ('DRIVER', 'Driver')], max_length=10)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
