# Generated by Django 5.0.1 on 2024-01-18 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 17, 14, 2, 84396, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
