# Generated by Django 5.0.1 on 2024-01-18 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 18, 17, 33, 27, 113369, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
