# Generated by Django 5.0.1 on 2024-01-19 10:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=300)),
                ('customer_name', models.CharField(max_length=300)),
                ('phone_number', models.BigIntegerField()),
                ('plaque', models.SmallIntegerField()),
                ('unit', models.SmallIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 10, 56, 30, 620501, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.CreateModel(
            name='Deliver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_as_destination', to='user.address')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_as_origin', to='user.address')),
            ],
        ),
    ]
