# Generated by Django 5.0 on 2024-03-01 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_otp_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 10, 42, 55, 329483, tzinfo=datetime.timezone.utc), editable=False),
        ),
    ]
